version: "3.2"
services:
  mongo:
    context: ./
      dockerfile: Dockerfile.mongo
      cache_from:
        - adnanrahic/alpine-mongo
    image: adnanrahic/alpine-mongo
    volumes:
      - mongo:/data/db
    networks: 
      backend:
        aliases:
          - mongo
    
  api:
    environment:
      - DB="${DB}"
      - SECRET=secretkey
      - NODE_ENV=prod
      - DB=mongodb://mongo:27017/boilerplate_api
      - PORT=3000
      - API_IMAGE=adnanrahic/boilerplate-api
    image: "${API_IMAGE}:${SEMAPHORE_GIT_BRANCH}"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./node_modules:/usr/src/app/node_modules
    networks: 
      backend:
        aliases:
          - api
      frontend:
        aliases:
          - api
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  client:
    environment:
      - CLIENT_IMAGE=adnanrahic/smoketest
    image: "${CLIENT_IMAGE}:${SEMAPHORE_GIT_BRANCH}"
    networks: 
      - frontend
    depends_on:
      - api
    ports:
      - "80:80"

networks: 
  backend:
  frontend:

volumes:
  mongo: