version: "3.2"
services:
  mongo:
    build:
      context: ./
      dockerfile: Dockerfile.mongo
    image: mongo:4.0
    volumes:
      - mongo:/data/db
    networks: 
      backend:
        aliases:
          - mongo
    
  api:
    environment:
      - DB="${DB}"
      - SECRET=secretkey
      - NODE_ENV=prod
      - DB=mongodb://mongo:27017/boilerplate_api
      - PORT=3000
      - API_IMAGE=adnanrahic/boilerplate-api
    image: "${API_IMAGE}:${TAG}"
    volumes:
      - ./logs:/usr/src/app/logs
    networks: 
      backend:
        aliases:
          - api
      frontend:
        aliases:
          - api
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  client:
    environment:
      - CLIENT_IMAGE=adnanrahic/smoketest
    image: "${CLIENT_IMAGE}:${TAG}"
    networks: 
      - frontend
    depends_on:
      - api
    ports:
      - "8080:80"

networks: 
  backend:
  frontend:

volumes:
  mongo: