version: "3.2"
services:
  mongo:
    build:
      context: ./
      dockerfile: Dockerfile.mongo
    image: mongo
    volumes:
      - mongo:/data/db
    networks: 
      backend:
        aliases:
          - mongo
    ports:
      - "27017:27017"
  
  api:
    env_file:
      - test.variables.env
    build:
      context: ./
      dockerfile: Dockerfile.test-unit
      cache_from:
        - ${IMAGE}
    image: "${IMAGE}:test-unit"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./node_modules:/usr/src/app/node_modules
    networks: 
      - backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"

networks: 
  backend:

volumes:
  mongo: