version: "3.2"
services:
  mongo:
    environment:
      - GET_HOSTS_FROM=dns
    image: mongo
    volumes:
      - mongo:/data/db
    
  api:
    environment:
      - DB="${DB}"
      - SECRET=secretkey
      - NODE_ENV=prod
      - DB=mongodb://mongo:27017/boilerplate_api
      - PORT=3000
      - API_IMAGE=adnanrahic/boilerplate-api
      - GET_HOSTS_FROM=dns
    image: "${API_IMAGE}"
    volumes:
      - logs:/usr/src/app/logs
    deploy:
      replicas: 6
    ports:
      - "3000"
    labels:
      kompose.service.type: LoadBalancer

  client:
    environment:
      - CLIENT_IMAGE=adnanrahic/smoketest
      - GET_HOSTS_FROM=dns
    image: "${CLIENT_IMAGE}"
    deploy:
      replicas: 6
    ports:
      - "80:80"
    labels:
      kompose.service.type: LoadBalancer

volumes:
  mongo:
  logs:


